#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://indranugraha.com" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

math_engine: katex
math_engine_opts: {}

permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page/:num"

# Pages Path
# defaults:
#   - scope:
#       path: '_pages'
#     values:
#       permalink: /:basename:output_ext
#   - scope:
#       path: '_posts'
#     values:
#       permalink: /blog/:slug

# include:
#   - _pages

sass:
  sass_dir: _sass
  style: compressed
